[workspace]
resolver = "3"
members = ["penguin-mux", "penguin", "async-acceptor", "penguin-socks", "cow-bytes"]
exclude = ["fuzz"]

[workspace.dependencies]
bytes = { version = "^1, >=1.11.1", default-features = false }
derive_more = { version = "2", default-features = false }
futures-util = { version = "0.3", default-features = false }
http-body-util = "0.1"
hyper = "1"
hyper-util = "0.1"
nohash-hasher = { version = "0.2", default-features = false }
parking_lot = "0.12"
rand = { version = "0.10", default-features = false }
thiserror = { version = "2", default-features = false }
tokio = "^1, >=1.23.1"
tokio-tungstenite = { version = "0.30", default-features = false }
tracing = { version = "0.1", features = ["attributes"], default-features = false }
tracing-subscriber = "^0.3, >=0.3.20"

[profile.release]
strip = true
codegen-units = 1
lto = true

[profile.profile]
inherits = "release"
debug = true
strip = false
panic = "unwind"

[profile.release-size]
inherits = "release"
opt-level = "z"
debug = false
strip = true
codegen-units = 1
lto = true
panic = "abort"

[workspace.metadata.cross.target.i686-pc-windows-gnu]
pre-build = ["apt-get update && apt-get -y install nasm"]

[workspace.metadata.cross.target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get -y install gcc-10 && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100"]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(dhat)', 'cfg(fuzzing)', 'cfg(loom)'] }
