# Temporary fix for cross-rs/cross#1345, tracking
[package.metadata.cross.target.x86_64-unknown-netbsd]
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl https://cdn.netbsd.org/pub/NetBSD/NetBSD-9.2/amd64/binary/sets/base.tar.xz -O",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]

# Fix libunwind linking on Android
[package.metadata.cross.target.aarch64-linux-android]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libunwind-dev:$CROSS_DEB_ARCH",
]

[package.metadata.cross.target.i686-linux-android]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libunwind-dev:$CROSS_DEB_ARCH",
]

[package.metadata.cross.target.x86_64-linux-android]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libunwind-dev:$CROSS_DEB_ARCH",
]
