#!/bin/sh

port=80
content="$2"
len="${#content}"

if [ "$1" = "create" ]; then
    socat TCP-LISTEN:$port,crlf,reuseaddr,fork SYSTEM:"sleep 1; echo 'HTTP/1.0 200 OK'; echo 'Content-Length: $len'; echo; printf '%s' '$content'" &
    pid=$!
    echo "$pid" > "/tmp/http01_socat_helper$content.pid6"
elif [ "$1" = "remove" ]; then
    if [ -f "/tmp/http01_socat_helper$content.pid6" ]; then
        pid=$(cat "/tmp/http01_socat_helper$content.pid6")
        rm -f "/tmp/http01_socat_helper$content.pid6"
        if [ -n "$pid" ]; then
            kill "$pid" 2>/dev/null || true
        fi
    fi
fi
