name: Rust Build and Test

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: aarch64-apple-darwin
          os: macos-latest
          codecov_os_name: macos
        - name: x86_64-unknown-linux-gnu
          os: ubuntu-latest
          codecov_os_name: linux
        - name: aarch64-unknown-linux-gnu
          os: ubuntu-24.04-arm
          codecov_os_name: linux-arm64
        - name: x86_64-pc-windows-msvc
          os: windows-latest
          codecov_os_name: windows
        - name: aarch64-pc-windows-msvc
          os: windows-11-arm
          codecov_os_name: windows
        tls:
        - nativetls
        - rustls-native-roots
        - rustls-webpki-roots

    steps:
    - uses: actions/checkout@v7

    - name: Install Rust toolchain
      run:
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --component llvm-tools-preview

    - name: Install grcov
      uses: baptiste0928/cargo-install@v3
      with:
        crate: grcov

    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-nextest

    - name: Set up Go for Pebble
      uses: actions/setup-go@v6
      with:
        go-version: '>=1.20.0'
        cache: false

    - name: Install and run pebble
      run: .github/workflows/pebble.sh

    - name: Run cargo tests
      run: .github/workflows/test-coverage.sh ${{ matrix.tls }} ${{ matrix.config.name }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v7
      with:
        report_type: test_results
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.tls }}-${{ matrix.config.name }}
        os: ${{ matrix.config.codecov_os_name }}

    - name: Upload coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v7
      with:
        fail_ci_if_error: false
        handle_no_reports_found: true
        files: ./debug.info,./release.info
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.tls }}-${{ matrix.config.name }}
        os: ${{ matrix.config.codecov_os_name }}
