name: Rust Build and Test

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Intel macOS
          os: macos-latest
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest
        tls:
        - nativetls
        - rustls-native-roots
        - rustls-webpki-roots

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      run:
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --component llvm-tools-preview

    - name: Install grcov
      uses: baptiste0928/cargo-install@v3
      with:
        crate: grcov

    - name: Install cargo-nextest
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-nextest

    - name: Set up Go for Pebble
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.20.0'
        cache: false

    - name: Install and run pebble
      run: .github/workflows/pebble.sh

    - name: Run cargo tests with more features on
      run: cargo nextest run --all-targets --verbose --features ${{ matrix.tls }},ring,tests-real-internet4,tests-acme-has-pebble,penguin-binary,acme,default-is-ipv6,tokio-console,deadlock-detection --no-default-features
      env:
        RUSTFLAGS: -Cinstrument-coverage

    - name: Run cargo tests with default features
      run: cargo nextest run --all-targets --verbose --features ${{ matrix.tls }},ring,tests-real-internet4,acme,penguin-binary --no-default-features
      env:
        RUSTFLAGS: -Cinstrument-coverage

    - name: Run cargo tests with the nohash hashmap
      run: cargo nextest run --all-targets --verbose --features ${{ matrix.tls }},ring,tests-real-internet4,acme,penguin-binary,nohash --no-default-features
      env:
        RUSTFLAGS: -Cinstrument-coverage

    - name: Run cargo lib tests with minimal features
      run: cargo nextest run --all-targets --verbose --no-default-features --package penguin-mux
      env:
        RUSTFLAGS: -Cinstrument-coverage

    - name: Run cargo lib tests with loom
      run: cargo test --lib --release --no-default-features --package penguin-mux
      env:
        RUSTFLAGS: --cfg loom -Cinstrument-coverage
        LOOM_LOG: debug

    - name: Process coverage data
      run: grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.tls }},${{ matrix.config.name }}

    - name: Upload coverage to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: false
        handle_no_reports_found: true
        files: ./lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.tls }},${{ matrix.config.name }}
